/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The request required to create a team
 * @export
 * @interface CreateTeamRequest
 */
export interface CreateTeamRequest {
  /**
   *
   * @type {string}
   * @memberof CreateTeamRequest
   */
  name: string;
  /**
   *
   * @type {Array<number>}
   * @memberof CreateTeamRequest
   */
  members: Array<number>;
}

export function CreateTeamRequestFromJSON(json: any): CreateTeamRequest {
  return CreateTeamRequestFromJSONTyped(json, false);
}

export function CreateTeamRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateTeamRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    members: json["members"],
  };
}

export function CreateTeamRequestToJSON(value?: CreateTeamRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    members: value.members,
  };
}
