/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The request required to create an event
 * @export
 * @interface CreateEventCommentRequest
 */
export interface CreateEventCommentRequest {
    /**
     *
     * @type {string}
     * @memberof CreateEventCommentRequest
     */
    comment: string;
}

export function CreateEventCommentRequestFromJSON(
    json: any
): CreateEventCommentRequest {
    return CreateEventCommentRequestFromJSONTyped(json, false);
}

export function CreateEventCommentRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateEventCommentRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        comment: json["comment"],
    };
}

export function CreateEventCommentRequestToJSON(
    value?: CreateEventCommentRequest | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        comment: value.comment,
    };
}
