/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The response of a successfully created event.
 * @export
 * @interface CreateEventResponse
 */
export interface CreateEventResponse {
    /**
     *
     * @type {number}
     * @memberof CreateEventResponse
     */
    eventId: number;
}

export function CreateEventResponseFromJSON(json: any): CreateEventResponse {
    return CreateEventResponseFromJSONTyped(json, false);
}

export function CreateEventResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateEventResponse {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        eventId: json["event_id"],
    };
}

export function CreateEventResponseToJSON(
    value?: CreateEventResponse | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        event_id: value.eventId,
    };
}
