/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { User, UserFromJSON, UserFromJSONTyped, UserToJSON } from "./";

/**
 * An event.
 * @export
 * @interface Event
 */
export interface Event {
  /**
   *
   * @type {number}
   * @memberof Event
   */
  eventId: number;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  description: string | null;
  /**
   *
   * @type {User}
   * @memberof Event
   */
  creator?: User;
  /**
   *
   * @type {Date}
   * @memberof Event
   */
  createdAt: Date;
}

export function EventFromJSON(json: any): Event {
  return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Event {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    eventId: json["event_id"],
    name: json["name"],
    description: json["description"],
    creator: !exists(json, "creator")
      ? undefined
      : UserFromJSON(json["creator"]),
    createdAt: new Date(json["created_at"]),
  };
}

export function EventToJSON(value?: Event | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    event_id: value.eventId,
    name: value.name,
    description: value.description,
    creator: UserToJSON(value.creator),
    created_at: value.createdAt.toISOString(),
  };
}
