/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * A friend of the currently logged in user.
 * @export
 * @interface Friend
 */
export interface Friend {
  /**
   *
   * @type {number}
   * @memberof Friend
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof Friend
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof Friend
   */
  avatar: string | null;
  /**
   *
   * @type {string}
   * @memberof Friend
   */
  taunt: string | null;
  /**
   *
   * @type {Date}
   * @memberof Friend
   */
  createdAt: Date;
}

export function FriendFromJSON(json: any): Friend {
  return FriendFromJSONTyped(json, false);
}

export function FriendFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Friend {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json["user_id"],
    username: json["username"],
    avatar: json["avatar"],
    taunt: json["taunt"],
    createdAt: new Date(json["created_at"]),
  };
}

export function FriendToJSON(value?: Friend | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user_id: value.userId,
    username: value.username,
    avatar: value.avatar,
    taunt: value.taunt,
    created_at: value.createdAt.toISOString(),
  };
}
