/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The request required to invite a member to the event
 * @export
 * @interface InviteMemberRequest
 */
export interface InviteMemberRequest {
    /**
     *
     * @type {number}
     * @memberof InviteMemberRequest
     */
    userId: number;
}

export function InviteMemberRequestFromJSON(json: any): InviteMemberRequest {
    return InviteMemberRequestFromJSONTyped(json, false);
}

export function InviteMemberRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): InviteMemberRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        userId: json["user_id"],
    };
}

export function InviteMemberRequestToJSON(
    value?: InviteMemberRequest | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        user_id: value.userId,
    };
}
