/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * A person that is logged in to tallii.
 * @export
 * @interface Me
 */
export interface Me {
  /**
   *
   * @type {number}
   * @memberof Me
   */
  userId: number;
  /**
   *
   * @type {string}
   * @memberof Me
   */
  avatar: string | null;
  /**
   *
   * @type {string}
   * @memberof Me
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof Me
   */
  inviteCode: string;
  /**
   *
   * @type {string}
   * @memberof Me
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof Me
   */
  taunt: string | null;
  /**
   *
   * @type {boolean}
   * @memberof Me
   */
  verified: boolean | null;
}

export function MeFromJSON(json: any): Me {
  return MeFromJSONTyped(json, false);
}

export function MeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Me {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json["user_id"],
    avatar: json["avatar"],
    email: json["email"],
    inviteCode: json["invite_code"],
    username: json["username"],
    taunt: json["taunt"],
    verified: json["verified"],
  };
}

export function MeToJSON(value?: Me | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user_id: value.userId,
    avatar: value.avatar,
    email: value.email,
    invite_code: value.inviteCode,
    username: value.username,
    taunt: value.taunt,
    verified: value.verified,
  };
}
