/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * The request required to update a member to the event
 * @export
 * @interface UpdateMemberRequest
 */
export interface UpdateMemberRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMemberRequest
   */
  state: UpdateMemberRequestStateEnum;
  /**
   *
   * @type {string}
   * @memberof UpdateMemberRequest
   */
  role: UpdateMemberRequestRoleEnum;
}

export function UpdateMemberRequestFromJSON(json: any): UpdateMemberRequest {
  return UpdateMemberRequestFromJSONTyped(json, false);
}

export function UpdateMemberRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateMemberRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    state: json["state"],
    role: json["role"],
  };
}

export function UpdateMemberRequestToJSON(
  value?: UpdateMemberRequest | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    state: value.state,
    role: value.role,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateMemberRequestStateEnum {
  Pending = "pending",
  Declined = "declined",
  Active = "active",
}
/**
 * @export
 * @enum {string}
 */
export enum UpdateMemberRequestRoleEnum {
  Member = "member",
  Admin = "admin",
}
