/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateEventRequest
 */
export interface UpdateEventRequest {
    /**
     *
     * @type {string}
     * @memberof UpdateEventRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof UpdateEventRequest
     */
    description: string;
}

export function UpdateEventRequestFromJSON(json: any): UpdateEventRequest {
    return UpdateEventRequestFromJSONTyped(json, false);
}

export function UpdateEventRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UpdateEventRequest {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        name: json["name"],
        description: json["description"],
    };
}

export function UpdateEventRequestToJSON(
    value?: UpdateEventRequest | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        name: value.name,
        description: value.description,
    };
}
