/* tslint:disable */
/* eslint-disable */
/**
 * Tallii API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * A person that is logged in to tallii.
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {number}
     * @memberof User
     */
    userId: number;
    /**
     *
     * @type {string}
     * @memberof User
     */
    emoji: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    bgColor: string | null;
    /**
     *
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    bio: string | null;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): User {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        userId: json["user_id"],
        emoji: json["emoji"],
        bgColor: json["bg_color"],
        username: json["username"],
        bio: json["bio"],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        user_id: value.userId,
        emoji: value.emoji,
        bg_color: value.bgColor,
        username: value.username,
        bio: value.bio,
    };
}
